---

- name: Install open-vm-tools.
  yum: "name={{ item }} state=present"
  with_items:
    - open-vm-tools
  when: not packer_full_vmware_tools

- include: vmware-full.yml
  when: packer_full_vmware_tools
