---
- include: build-packages.yml

- name: Add vmhgfs module (RHEL 6).
  template:
    src: vmhgfs.modules.j2
    dest: /etc/sysconfig/modules/vmhgfs.modules
    mode: 0755
  when: ansible_distribution_major_version|int <= 6

- name: Create temporary directories for VMware tools.
  file:
    path: "/tmp/{{ item }}"
    state: directory
  with_items:
    - vmfusion
    - vmfusion-archive

- command: ls -lah /home/vagrant
  register: vaglist
- debug: var=vaglist

- name: Mount VMware tools.
  mount:
    name: /tmp/vmfusion
    src: /home/vagrant/linux.iso
    fstype: iso9660
    opts: loop
    state: mounted

- name: Decompress VMware Tools installer into archive folder.
  shell: tar xzf /tmp/vmfusion/VMwareTools-*.tar.gz -C /tmp/vmfusion-archive

- name: Run the VMware tools installer.
  shell: /tmp/vmfusion-archive/vmware-tools-distrib/vmware-install.pl --default

- name: Unmount VMware tools.
  mount:
    name: /tmp/vmfusion
    src: /home/vagrant/linux.iso
    fstype: iso9660
    state: absent

- name: Remove temporary directories for VMware tools.
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - vmfusion
    - vmfusion-archive

- name: Delete VMware Tools.
  file:
    path: /home/vagrant/linux.iso
    state: absent
